<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create a demo landlord if none exists
        $landlord = User::where('role', 'landlord')->first();
        
        if (!$landlord) {
            $landlord = User::create([
                'name' => 'Demo Landlord',
                'email' => 'landlord@propconnect.demo',
                'password' => Hash::make('password123'),
                'role' => 'landlord',
                'phone' => '+63 912 345 6789',
                'is_verified' => true,
            ]);
        }

        // Sample properties in Cebu City
        $properties = [
            [
                'title' => 'Modern Studio in IT Park',
                'description' => 'Fully furnished studio unit in the heart of Cebu IT Park. Perfect for young professionals. Walking distance to restaurants, cafes, and offices. 24/7 security, swimming pool, and gym access included.',
                'property_type' => 'studio',
                'price' => 18000,
                'deposit' => 36000,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor_area' => 28,
                'floor_number' => 12,
                'address' => 'Avida Towers IT Park, Lahug',
                'city' => 'Cebu City',
                'latitude' => 10.3271,
                'longitude' => 123.9056,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'security', 'elevator'],
                'is_featured' => true,
            ],
            [
                'title' => 'Cozy 1BR Condo at Baseline',
                'description' => 'Spacious 1-bedroom condo with city views. Located in the popular Baseline Center with shopping mall access. Fully furnished with modern appliances.',
                'property_type' => 'condo',
                'price' => 22000,
                'deposit' => 44000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor_area' => 35,
                'floor_number' => 8,
                'address' => 'Baseline Residences, Cebu Business Park',
                'city' => 'Cebu City',
                'latitude' => 10.3182,
                'longitude' => 123.8933,
                'amenities' => ['wifi', 'aircon', 'furnished', 'parking', 'security', 'elevator'],
                'is_featured' => true,
            ],
            [
                'title' => 'Spacious 2BR near SM City',
                'description' => 'Large 2-bedroom apartment just 5 minutes from SM City Cebu. Great for families. Pet-friendly building with playground for kids.',
                'property_type' => 'apartment',
                'price' => 28000,
                'deposit' => 56000,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'floor_area' => 55,
                'floor_number' => 5,
                'address' => 'Mango Avenue, Capitol Site',
                'city' => 'Cebu City',
                'latitude' => 10.3084,
                'longitude' => 123.8935,
                'amenities' => ['wifi', 'aircon', 'kitchen', 'washer', 'pet_friendly', 'parking'],
                'is_featured' => false,
            ],
            [
                'title' => 'Luxury Penthouse at Ayala',
                'description' => 'Premium penthouse unit with panoramic city and sea views. 3 bedrooms, modern kitchen, private balcony. Located in the prestigious Ayala Center Cebu area.',
                'property_type' => 'condo',
                'price' => 85000,
                'deposit' => 170000,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'floor_area' => 120,
                'floor_number' => 25,
                'address' => 'The Alcoves, Ayala Center Cebu',
                'city' => 'Cebu City',
                'latitude' => 10.3190,
                'longitude' => 123.9050,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'security', 'elevator', 'balcony', 'parking'],
                'is_featured' => true,
            ],
            [
                'title' => 'Budget-Friendly Room in Banilad',
                'description' => 'Affordable private room in a shared house. Perfect for students near UPCEBU. All utilities included in the rent.',
                'property_type' => 'room',
                'price' => 8000,
                'deposit' => 16000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor_area' => 15,
                'floor_number' => 1,
                'address' => 'Gov. M. Cuenco Ave, Banilad',
                'city' => 'Cebu City',
                'latitude' => 10.3419,
                'longitude' => 123.9112,
                'amenities' => ['wifi', 'furnished'],
                'is_featured' => false,
            ],
            [
                'title' => 'Brand New 2BR in Talamban',
                'description' => 'Newly constructed 2-bedroom apartment in a quiet residential area. Near universities and hospitals. Great for families or students.',
                'property_type' => 'apartment',
                'price' => 20000,
                'deposit' => 40000,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floor_area' => 48,
                'floor_number' => 3,
                'address' => 'Nasipit, Talamban',
                'city' => 'Cebu City',
                'latitude' => 10.3545,
                'longitude' => 123.9123,
                'amenities' => ['wifi', 'aircon', 'kitchen', 'parking'],
                'is_featured' => false,
            ],
            [
                'title' => 'Stylish Loft at One Pavilion',
                'description' => 'Unique loft-style condo with high ceilings. Modern design, fully furnished. Located near the Cebu Provincial Capitol.',
                'property_type' => 'condo',
                'price' => 32000,
                'deposit' => 64000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor_area' => 42,
                'floor_number' => 6,
                'address' => 'One Pavilion Place, Capitol Site',
                'city' => 'Cebu City',
                'latitude' => 10.3099,
                'longitude' => 123.8912,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'elevator'],
                'is_featured' => false,
            ],
            [
                'title' => 'Family House in Mabolo',
                'description' => '3-bedroom house with front and back yard. Private parking for 2 cars. Quiet neighborhood, near schools and churches.',
                'property_type' => 'house',
                'price' => 45000,
                'deposit' => 90000,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floor_area' => 90,
                'floor_number' => null,
                'address' => 'Mabolo Proper',
                'city' => 'Cebu City',
                'latitude' => 10.3226,
                'longitude' => 123.9029,
                'amenities' => ['wifi', 'aircon', 'kitchen', 'parking', 'pet_friendly', 'washer', 'dryer'],
                'is_featured' => false,
            ],
            [
                'title' => 'Executive Suite at Marco Polo',
                'description' => 'Hotel-style living in the famous Marco Polo Plaza. Includes housekeeping, room service, and access to all hotel amenities.',
                'property_type' => 'hotel',
                'price' => 65000,
                'deposit' => 130000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor_area' => 45,
                'floor_number' => 18,
                'address' => 'Marco Polo Plaza, Nivel Hills',
                'city' => 'Cebu City',
                'latitude' => 10.3280,
                'longitude' => 123.8990,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'security', 'tv'],
                'is_featured' => true,
            ],
            [
                'title' => 'Affordable Studio in Ramos',
                'description' => 'Clean and well-maintained studio near Fuente Osmeña. Walking distance to malls, restaurants, and public transport.',
                'property_type' => 'studio',
                'price' => 12000,
                'deposit' => 24000,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floor_area' => 22,
                'floor_number' => 4,
                'address' => 'Ramos Street Extension',
                'city' => 'Cebu City',
                'latitude' => 10.3105,
                'longitude' => 123.8888,
                'amenities' => ['wifi', 'aircon'],
                'is_featured' => false,
            ],
            [
                'title' => 'Sea View Condo in SRP',
                'description' => 'Modern condo with stunning sea views. Located in the new SRP development. Near SM Seaside City.',
                'property_type' => 'condo',
                'price' => 38000,
                'deposit' => 76000,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'floor_area' => 58,
                'floor_number' => 15,
                'address' => 'The Reef Residences, SRP',
                'city' => 'Cebu City',
                'latitude' => 10.2899,
                'longitude' => 123.8755,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'security', 'balcony'],
                'is_featured' => false,
            ],
            [
                'title' => 'Cozy 1BR near Ayala',
                'description' => 'Well-appointed 1-bedroom condo in Cebu Business Park. Minutes from Ayala Center. Includes parking slot.',
                'property_type' => 'condo',
                'price' => 25000,
                'deposit' => 50000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floor_area' => 38,
                'floor_number' => 10,
                'address' => 'Solinea Tower, Cebu Business Park',
                'city' => 'Cebu City',
                'latitude' => 10.3175,
                'longitude' => 123.9010,
                'amenities' => ['wifi', 'aircon', 'furnished', 'pool', 'gym', 'parking', 'elevator'],
                'is_featured' => false,
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create([
                'landlord_id' => $landlord->id,
                'status' => 'available',
                'views_count' => rand(50, 500),
                'is_verified' => true,
                ...$propertyData,
            ]);
        }

        $this->command->info('Created ' . count($properties) . ' sample properties!');
    }
}
